export const colors = [
  { name: 'red', value: '#FF0000' },
  { name: 'green', value: '#00FF00' },
  { name: 'blue', value: '#0000FF' },
  { name: 'yellow', value: '#FFFF00' },
  { name: 'cyan', value: '#00FFFF' },
  { name: 'magenta', value: '#FF00FF' },
  { name: 'black', value: '#000000' },
  { name: 'white', value: '#FFFFFF' },
  { name: 'gray', value: '#808080' },
  { name: 'maroon', value: '#800000' },
  { name: 'olive', value: '#808000' },
  { name: 'purple', value: '#800080' },
  { name: 'teal', value: '#008080' },
  { name: 'navy', value: '#000080' },
  { name: 'silver', value: '#C0C0C0' },
  { name: 'lime', value: '#00FF00' },
  { name: 'aqua', value: '#00FFFF' },
  { name: 'fuchsia', value: '#FF00FF' },
  { name: 'orange', value: '#FFA500' },
  { name: 'brown', value: '#A52A2A' },
];
